spring:
  application: 
    name: guli-demo1
  profiles:
    active: dev
  datasource:
    username:  root
    password: Root
    url: jdbc:mysql://localhost:3306/testjdbc?characterEncoding=UTF-8&useSSL=false&serverTimezone=GMT%2B8&rewriteBatchedStatements=true
    driver-class-name: com.mysql.cj.jdbc.Driver
 
server:
  port: 8002