spring:
  application: 
    name: GULI-COS
  profiles:
    active: dev
      
  datasource:
    username:  root
    password: Root
    url: jdbc:mysql://localhost:3306/guli_0401?characterEncoding=UTF-8&useSSL=false&serverTimezone=GMT%2B8&rewriteBatchedStatements=true
    driver-class-name: com.mysql.cj.jdbc.Driver
  

  

    
server:
  port: 7200

  
swagger2:
  enable: true
  
